src/Entity/Student.php
<?php

namespace App\Entity;

use App\Repository\StudentRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=StudentRepository::class)
 */
class Student
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $student_number;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $course;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $year_level;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStudentNumber(): ?string
    {
        return $this->student_number;
    }

    public function setStudentNumber(string $student_number): self
    {
        $this->student_number = $student_number;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCourse(): ?string
    {
        return $this->course;
    }

    public function setCourse(string $course): self
    {
        $this->course = $course;

        return $this;
    }

    public function getYearLevel(): ?string
    {
        return $this->year_level;
    }

    public function setYearLevel(string $year_level): self
    {
        $this->year_level = $year_level;

        return $this;
    }
}

src/Form/StudentType.php
<?php

namespace App\Form;

use App\Entity\Student;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;


class StudentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('student_number')
            ->add('name')
            ->add('course' , ChoiceType::class, [
                'choices'  => [
                    'Select' => null,
                    'Bachelor of Science in Mechanical Engineering (BSME)' => 'Bachelor of Science in Mechanical Engineering (BSME)',
                    'Bachelor of Science in Electronics Engineering (BSECE)' => 'Bachelor of Science in Electronics Engineering (BSECE)',
                    'Bachelor of Science in Information Technology (BSIT)' => 'Bachelor of Science in Information Technology (BSIT)',
                    'Bachelor of Science in Education - Major in English (BSED-ENG)' => 'Bachelor of Science in Education - Major in English (BSED-ENG)',
                    'Bachelor of Science in Education - Major in Math (BSED-Math)' => 'Bachelor of Science in Education - Major in Math (BSED-Math)',
                    'Bachelor of Science in Accountancy (BSA)' => 'Bachelor of Science in Accountancy (BSA)',
                    'Bachelor of Science in Office Administration (BSOA)' => 'Bachelor of Science in Office Administration (BSOA)',
                    'Bachelor of Science in Business Administration - Marketing Management (BSBA-MM)' => 'Bachelor of Science in Business Administration - Marketing Management (BSBA-MM)',
                    'Bachelor of Science in Business Administration - Human Resource Management (BSBA-HRM)' => 'Bachelor of Science in Business Administration - Human Resource Management (BSBA-HRM)',
                    'Diploma in Information and Communication Technology (DICT)' => 'Diploma in Information and Communication Technology (DICT)',
                    'Diploma in Office Management Technology (DOMT)' => 'Diploma in Office Management Technology (DOMT)'

                ]
            ])
            ->add('year_level'  , ChoiceType::class, [
                'choices'  => [
                    'Select' => null,
                    '1st Year' => '1st Year',
                    '2nd Year' => '2nd Year',
                    '3rd Year' => '3rd Year',
                    '4th Year' => '4th Year',
                    '5th Year' => '5th Year',
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Student::class,
        ]);
    }
}

src/Controller/StudentController.php
<?php

namespace App\Controller;

use App\Entity\Student;
use App\Form\StudentType;
use App\Repository\StudentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/")
 */
class StudentController extends AbstractController
{
    /**
     * @Route("/", name="student_index", methods={"GET"})
     */
    public function index(StudentRepository $studentRepository): Response
    {
        return $this->render('student/index.html.twig', [
            'students' => $studentRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="student_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $student = new Student();
        $form = $this->createForm(StudentType::class, $student);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($student);
            $entityManager->flush();

            return $this->redirectToRoute('student_index');
        }

        return $this->render('student/new.html.twig', [
            'student' => $student,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="student_show", methods={"GET"})
     */
    public function show(Student $student): Response
    {
        return $this->render('student/show.html.twig', [
            'student' => $student,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="student_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Student $student): Response
    {
        $form = $this->createForm(StudentType::class, $student);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('student_index');
        }

        return $this->render('student/edit.html.twig', [
            'student' => $student,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="student_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Student $student): Response
    {
        if ($this->isCsrfTokenValid('delete'.$student->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($student);
            $entityManager->flush();
        }

        return $this->redirectToRoute('student_index');
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Simple CRUD Project{% endblock %}</title>
    {% block stylesheets %}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Spartan&display=swap">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous" />
        <link rel="stylesheet" href="{{ asset('/css/style.css') }}">
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-light bg-light"  style="height: 75px;">
    <a class="navbar-brand ms-5" href="#">
        <i class="fas fa-code"></i>
        <p class="pl-2 d-inline fw-bold">Simple CRUD Project</p>
    </a>
</nav>
{% block body %}{% endblock %}
<footer class="mt-5 p-3 text-center font-weight-normal text-muted">
    <p> Coded by <a href="https://github.com/fernandezjn">Jillian Noreen Fernandez</a> </p>
</footer>


{% block scripts %}
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
{% endblock %}
</body>
</html>

templates/student/_delete_form.html.twig
<form method="post" action="{{ path('student_delete', {'id': student.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ student.id) }}">
    <button class="btn btn-danger btn-sm"><i class="far fa-trash-alt"></i> Delete</button>
</form>

templates/student/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary btn-sm mt-5 float-end"><i class="far fa-save"></i> {{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/student/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Student Data{% endblock %}

{% block body %}
    <div class="container pt-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <h5 class="card-header fw-bold">Edit Student Data</h5>
                    <div class="card-body">
                        {{ include('student/_form.html.twig', {'button_label': 'Update'}) }}
                        <a class="btn btn-secondary btn-sm mt-5" href="{{ path('student_index') }}"><i class="far fa-arrow-alt-circle-left"></i> Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/student/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Simple CRUD{% endblock %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card mt-5">
                    <div class="card-header">
                        <h5 class="fw-bold align-middle d-inline">List of Students</h5>
                        <a class="btn btn-primary btn-sm float-end d-inline" href="{{ path('student_new') }}"><i class="far fa-plus-square me-1"></i> Add New Student</a>
                    </div>
                    <div class="card-body">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Id</th>
                                <th>Student Number</th>
                                <th>Name</th>
                                <th>Course</th>
                                <th>Year Level</th>
                                <th>Actions</th>

                            </tr>
                            </thead>
                            <tbody>
                            {% for student in students %}
                                <tr>
                                    <td>{{ student.id }}</td>
                                    <td>{{ student.studentNumber }}</td>
                                    <td>{{ student.name }}</td>
                                    <td>{{ student.course }}</td>
                                    <td>{{ student.yearLevel }}</td>
                                    <td>
                                        <a class="btn btn-primary btn-sm d-inline" href="{{ path('student_show', {'id': student.id}) }}"><i class="far fa-eye"></i> Show</a>
                                        <a class="btn btn-secondary btn-sm d-inline" href="{{ path('student_edit', {'id': student.id}) }}"><i class="far fa-edit"></i> Edit</a>
                                    </td>
                                </tr>
                            {% else %}
                                <tr>
                                    <td colspan="6">No Records Found</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/student/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add New Student{% endblock %}

{% block body %}
    <div class="container pt-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <h5 class="card-header fw-bold">Add New Student</h5>
                    <div class="card-body">
                        {{ include('student/_form.html.twig') }}
                        <a class="btn btn-secondary btn-sm mt-5" href="{{ path('student_index') }}"><i class="far fa-arrow-alt-circle-left"></i> Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/student/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}View Student{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card mt-5 ">
                    <h5 class="card-header fw-bold">View Student</h5>
                    <div class="card-body">
                        <table class="table">
                            <tbody>
                            <tr>
                                <th>Id</th>
                                <td>{{ student.id }}</td>
                            </tr>
                            <tr>
                                <th>Student_number</th>
                                <td>{{ student.studentNumber }}</td>
                            </tr>
                            <tr>
                                <th>Name</th>
                                <td>{{ student.name }}</td>
                            </tr>
                            <tr>
                                <th>Course</th>
                                <td>{{ student.course }}</td>
                            </tr>
                            <tr>
                                <th>Year_level</th>
                                <td>{{ student.yearLevel }}</td>
                            </tr>
                            </tbody>
                        </table>

                    </div>
                    <div class="card-footer">
                        <div class="d-flex bd-highlight">
                            <div class="me-auto bd-highlight">
                                <a class="btn btn-primary btn-sm" href="{{ path('student_index') }}"><i class="far fa-arrow-alt-circle-left"></i> Back</a>
                            </div>
                            <div class="bd-highlight">
                                <a class="btn btn-secondary btn-sm mx-1" href="{{ path('student_edit', {'id': student.id}) }}"><i class="far fa-edit"></i> Edit</a>
                            </div>
                            <div class="bd-highlight">{{ include('student/_delete_form.html.twig') }}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




{% endblock %}